# Generated by Django 5.2.17 on 2026-09-28 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='must_change_password',
        ),
    ]
