# Generated by Django 5.2.17 on 2026-09-24 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=80)),
                ('town', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=160)),
                ('date_opened', models.DateField()),
            ],
            options={
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=80)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('date_registered', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.PROTECT, to='clinic.branch')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=40)),
                ('species', models.CharField(blank=True, max_length=15, null=True)),
                ('breed', models.CharField(blank=True, max_length=40, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('color_marking', models.CharField(blank=True, max_length=40, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(db_default='Active', default='Active', max_length=20)),
                ('follow_up_note', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='clinic.customer')),
            ],
            options={
                'db_table': 'pet',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=60)),
                ('role', models.CharField(max_length=40)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=160, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.PROTECT, to='clinic.branch')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('record_id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('record_date', models.DateField()),
                ('record_type', models.CharField(blank=True, max_length=30, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=200, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=40, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('availed_items', models.JSONField(blank=True, db_default=[], default=list)),
                ('total_price', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=12)),
                ('blood_test_image', models.TextField(blank=True, null=True)),
                ('blood_test_name', models.CharField(blank=True, max_length=200, null=True)),
                ('waiver_image', models.TextField(blank=True, null=True)),
                ('waiver_name', models.CharField(blank=True, max_length=200, null=True)),
                ('follow_up', models.BooleanField(db_default=False, default=False)),
                ('follow_up_note', models.CharField(blank=True, max_length=200, null=True)),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.PROTECT, to='clinic.branch')),
                ('pet', models.ForeignKey(db_column='pet_id', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='clinic.pet')),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.staff')),
            ],
            options={
                'db_table': 'medical_record',
            },
        ),
    ]
