# Generated by Django 5.2.17 on 2026-09-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='source_txn_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
