# Generated by Django 5.2.17 on 2026-09-24 07:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('txn_id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('txn_type', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity_change', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=16, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('txn_date', models.DateField()),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, to='clinic.branch')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.staff')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'db_table': 'inventory_transaction',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reorder_point', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reorder_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_counted', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, to='clinic.branch')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.product')),
            ],
            options={
                'db_table': 'inventory',
                'constraints': [models.UniqueConstraint(fields=('product', 'branch'), name='inventory_product_branch_uq')],
            },
        ),
        migrations.CreateModel(
            name='ProductBranchPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_capital', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, to='clinic.branch')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='inventory.product')),
            ],
            options={
                'db_table': 'product_branch_price',
                'constraints': [models.UniqueConstraint(fields=('product', 'branch'), name='product_branch_price_uq'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='chk_pbp_price')],
            },
        ),
        migrations.CreateModel(
            name='ServiceBranchPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('unit_capital', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, to='clinic.branch')),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.service')),
            ],
            options={
                'db_table': 'service_branch_price',
                'constraints': [models.UniqueConstraint(fields=('service', 'branch'), name='service_branch_price_uq'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='chk_sbp_price')],
            },
        ),
        migrations.CreateModel(
            name='ServiceProductUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per_service', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.service')),
            ],
            options={
                'db_table': 'service_product_usage',
                'constraints': [models.UniqueConstraint(fields=('service', 'product'), name='service_product_usage_uq')],
            },
        ),
    ]
