# Generated by Django 5.2.17 on 2026-09-24 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('sale_date', models.DateField()),
                ('sale_time', models.TimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=15, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=15, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.PROTECT, to='clinic.branch')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clinic.staff')),
                ('customer', models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.customer')),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='clinic.staff')),
            ],
            options={
                'db_table': 'sale',
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('sale_detail_id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('unit_capital', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('line_capital', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('line_profit', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('pet', models.ForeignKey(blank=True, db_column='pet_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.pet')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('sale', models.ForeignKey(db_column='sale_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales.sale')),
            ],
            options={
                'db_table': 'sale_detail',
            },
        ),
        migrations.CreateModel(
            name='ServiceTransaction',
            fields=[
                ('service_txn_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('txn_date', models.DateField()),
                ('txn_time', models.TimeField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=15, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=15, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.PROTECT, to='clinic.branch')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clinic.staff')),
                ('customer', models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.customer')),
                ('pet', models.ForeignKey(blank=True, db_column='pet_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.pet')),
            ],
            options={
                'db_table': 'service_transaction',
            },
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('service_detail_id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('unit_capital', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('line_capital', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('line_profit', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('remarks', models.CharField(blank=True, max_length=120, null=True)),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.PROTECT, to='inventory.service')),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.staff')),
                ('service_txn', models.ForeignKey(db_column='service_txn_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales.servicetransaction')),
            ],
            options={
                'db_table': 'service_detail',
            },
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('payment_status__in', ['Paid', 'Unpaid', 'Partial', 'Pending', 'Refunded'])), name='chk_sale_payment_status'),
        ),
        migrations.AddConstraint(
            model_name='saledetail',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='chk_sd_qty'),
        ),
        migrations.AddConstraint(
            model_name='servicetransaction',
            constraint=models.CheckConstraint(condition=models.Q(('payment_status__in', ['Paid', 'Unpaid', 'Partial', 'Pending', 'Refunded'])), name='chk_service_payment_status'),
        ),
        migrations.AddConstraint(
            model_name='servicedetail',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='chk_vd_qty'),
        ),
    ]
