"""
Triggers, sequences and analytics views carried over verbatim from vetvisiondb.sql.

- trg_sale_detail_inventory / trg_service_detail_inventory deduct stock (and log
  inventory_transaction) automatically when a sale/service line is inserted, so the API
  must never deduct stock itself.
- v_* views feed the analytics endpoints.
"""
from django.db import migrations

FORWARD = [
    'CREATE SEQUENCE IF NOT EXISTS public.seq_inventory_id START 1;',
    'CREATE SEQUENCE IF NOT EXISTS public.seq_inv_txn_id START 1;',
    "CREATE OR REPLACE FUNCTION public.fn_inventory_deduct_on_sale() RETURNS trigger\n    LANGUAGE plpgsql\n    AS $$\nDECLARE\n    v_branch_id VARCHAR(10);\nBEGIN\n    SELECT branch_id INTO v_branch_id FROM sale WHERE sale_id = NEW.sale_id;\n    IF v_branch_id IS NULL THEN\n        RETURN NEW;  -- safety: no matching sale header, skip silently\n    END IF;\n\n    UPDATE inventory\n       SET quantity_on_hand = quantity_on_hand - NEW.quantity\n     WHERE product_id = NEW.product_id AND branch_id = v_branch_id;\n\n    IF NOT FOUND THEN\n        INSERT INTO inventory (inventory_id, product_id, branch_id, quantity_on_hand)\n        VALUES ('INV-' || lpad(nextval('seq_inventory_id')::text, 6, '0'),\n                NEW.product_id, v_branch_id, -NEW.quantity);\n    END IF;\n\n    INSERT INTO inventory_transaction\n        (txn_id, product_id, branch_id, txn_type, quantity_change, reference_id, remarks, txn_date)\n    VALUES\n        ('ITX-' || lpad(nextval('seq_inv_txn_id')::text, 8, '0'),\n         NEW.product_id, v_branch_id, 'sale', -NEW.quantity, NEW.sale_id,\n         'Auto-deducted: product sold', CURRENT_DATE);\n\n    RETURN NEW;\nEND;\n$$;\n",
    "CREATE OR REPLACE FUNCTION public.fn_inventory_deduct_on_service() RETURNS trigger\n    LANGUAGE plpgsql\n    AS $$\nDECLARE\n    v_branch_id VARCHAR(10);\n    v_usage     RECORD;\n    v_deduct    NUMERIC(10,2);\nBEGIN\n    SELECT branch_id INTO v_branch_id\n      FROM service_transaction\n     WHERE service_txn_id = NEW.service_txn_id;\n\n    IF v_branch_id IS NULL THEN\n        RETURN NEW;  -- safety: no matching transaction header, skip silently\n    END IF;\n\n    -- a service may use zero, one, or several products; loop through\n    -- whatever service_product_usage says this service consumes\n    FOR v_usage IN\n        SELECT product_id, qty_per_service\n          FROM service_product_usage\n         WHERE service_id = NEW.service_id\n    LOOP\n        v_deduct := v_usage.qty_per_service * NEW.quantity;\n\n        UPDATE inventory\n           SET quantity_on_hand = quantity_on_hand - v_deduct\n         WHERE product_id = v_usage.product_id AND branch_id = v_branch_id;\n\n        IF NOT FOUND THEN\n            INSERT INTO inventory (inventory_id, product_id, branch_id, quantity_on_hand)\n            VALUES ('INV-' || lpad(nextval('seq_inventory_id')::text, 6, '0'),\n                    v_usage.product_id, v_branch_id, -v_deduct);\n        END IF;\n\n        INSERT INTO inventory_transaction\n            (txn_id, product_id, branch_id, txn_type, quantity_change, reference_id, remarks, txn_date)\n        VALUES\n            ('ITX-' || lpad(nextval('seq_inv_txn_id')::text, 8, '0'),\n             v_usage.product_id, v_branch_id, 'service_usage', -v_deduct, NEW.service_txn_id,\n             'Auto-deducted: used in service ' || NEW.service_id, CURRENT_DATE);\n    END LOOP;\n\n    RETURN NEW;\nEND;\n$$;\n",
    'DROP TRIGGER IF EXISTS trg_sale_detail_inventory ON public.sale_detail;',
    'CREATE TRIGGER trg_sale_detail_inventory AFTER INSERT ON public.sale_detail FOR EACH ROW EXECUTE FUNCTION public.fn_inventory_deduct_on_sale();',
    'DROP TRIGGER IF EXISTS trg_service_detail_inventory ON public.service_detail;',
    'CREATE TRIGGER trg_service_detail_inventory AFTER INSERT ON public.service_detail FOR EACH ROW EXECUTE FUNCTION public.fn_inventory_deduct_on_service();',
    "CREATE OR REPLACE VIEW public.v_sale_lines AS\n SELECT s.sale_id,\n    s.branch_id,\n    b.branch_name,\n    s.sale_date,\n    (date_trunc('month'::text, (s.sale_date)::timestamp with time zone))::date AS month,\n    s.staff_id,\n    st.staff_name,\n    s.customer_id,\n    c.customer_name,\n    d.product_id,\n    p.product_name,\n    p.category,\n    d.quantity,\n    d.line_total,\n    d.line_capital,\n    d.line_profit,\n    s.payment_method,\n    s.payment_status\n   FROM (((((public.sale s\n     JOIN public.branch b ON (((b.branch_id)::text = (s.branch_id)::text)))\n     LEFT JOIN public.staff st ON (((st.staff_id)::text = (s.staff_id)::text)))\n     LEFT JOIN public.customer c ON (((c.customer_id)::text = (s.customer_id)::text)))\n     JOIN public.sale_detail d ON (((d.sale_id)::text = (s.sale_id)::text)))\n     JOIN public.product p ON (((p.product_id)::text = (d.product_id)::text)));\n",
    "CREATE OR REPLACE VIEW public.v_service_lines AS\n SELECT t.service_txn_id,\n    t.branch_id,\n    b.branch_name,\n    t.txn_date,\n    (date_trunc('month'::text, (t.txn_date)::timestamp with time zone))::date AS month,\n    t.customer_id,\n    c.customer_name,\n    t.pet_id,\n    pe.pet_name,\n    pe.species,\n    t.weight_kg,\n    d.service_id,\n    sv.service_name,\n    sv.category,\n    d.staff_id,\n    st.staff_name,\n    st.role,\n    d.quantity,\n    d.line_total,\n    d.line_capital,\n    d.line_profit,\n    d.remarks,\n    t.payment_method,\n    t.payment_status\n   FROM ((((((public.service_transaction t\n     JOIN public.branch b ON (((b.branch_id)::text = (t.branch_id)::text)))\n     LEFT JOIN public.customer c ON (((c.customer_id)::text = (t.customer_id)::text)))\n     LEFT JOIN public.pet pe ON (((pe.pet_id)::text = (t.pet_id)::text)))\n     JOIN public.service_detail d ON (((d.service_txn_id)::text = (t.service_txn_id)::text)))\n     JOIN public.service sv ON (((sv.service_id)::text = (d.service_id)::text)))\n     LEFT JOIN public.staff st ON (((st.staff_id)::text = (d.staff_id)::text)));\n",
    'CREATE OR REPLACE VIEW public.v_branch_monthly_kpi AS\n WITH sales_m AS (\n         SELECT v_sale_lines.branch_id,\n            v_sale_lines.month,\n            count(DISTINCT v_sale_lines.sale_id) AS sale_txns,\n            sum(v_sale_lines.line_total) AS sales_gross,\n            sum(v_sale_lines.line_profit) AS sales_profit\n           FROM public.v_sale_lines\n          GROUP BY v_sale_lines.branch_id, v_sale_lines.month\n        ), svc_m AS (\n         SELECT v_service_lines.branch_id,\n            v_service_lines.month,\n            count(DISTINCT v_service_lines.service_txn_id) AS service_txns,\n            sum(v_service_lines.line_total) AS service_gross,\n            sum(v_service_lines.line_profit) AS service_profit\n           FROM public.v_service_lines\n          GROUP BY v_service_lines.branch_id, v_service_lines.month\n        ), grid AS (\n         SELECT sales_m.branch_id,\n            sales_m.month\n           FROM sales_m\n        UNION\n         SELECT svc_m.branch_id,\n            svc_m.month\n           FROM svc_m\n        )\n SELECT g.branch_id,\n    b.branch_name,\n    g.month,\n    COALESCE(s.sale_txns, (0)::bigint) AS sale_txns,\n    COALESCE(v.service_txns, (0)::bigint) AS service_txns,\n    COALESCE(s.sales_gross, (0)::numeric) AS sales_gross,\n    COALESCE(v.service_gross, (0)::numeric) AS service_gross,\n    (COALESCE(s.sales_gross, (0)::numeric) + COALESCE(v.service_gross, (0)::numeric)) AS total_gross,\n    (COALESCE(s.sales_profit, (0)::numeric) + COALESCE(v.service_profit, (0)::numeric)) AS total_profit\n   FROM (((grid g\n     JOIN public.branch b ON (((b.branch_id)::text = (g.branch_id)::text)))\n     LEFT JOIN sales_m s ON ((((s.branch_id)::text = (g.branch_id)::text) AND (s.month = g.month))))\n     LEFT JOIN svc_m v ON ((((v.branch_id)::text = (g.branch_id)::text) AND (v.month = g.month))));\n',
    "CREATE OR REPLACE VIEW public.v_fast_movers AS\n SELECT branch_id,\n    branch_name,\n    product_id,\n    product_name,\n    category,\n    sum(quantity) AS units_sold,\n    sum(line_total) AS revenue,\n    count(*) AS times_sold\n   FROM public.v_sale_lines\n  WHERE (sale_date >= ( SELECT (max(sale.sale_date) - '90 days'::interval)\n           FROM public.sale))\n  GROUP BY branch_id, branch_name, product_id, product_name, category\n  ORDER BY (sum(quantity)) DESC;\n",
    "CREATE OR REPLACE VIEW public.v_slow_movers AS\n SELECT b.branch_id,\n    b.branch_name,\n    p.product_id,\n    p.product_name,\n    p.category,\n    COALESCE(sum(l.quantity), (0)::bigint) AS units_sold,\n    COALESCE(sum(l.line_total), (0)::numeric) AS revenue\n   FROM ((public.product p\n     CROSS JOIN public.branch b)\n     LEFT JOIN public.v_sale_lines l ON ((((l.product_id)::text = (p.product_id)::text) AND ((l.branch_id)::text = (b.branch_id)::text) AND (l.sale_date >= ( SELECT (max(sale.sale_date) - '90 days'::interval)\n           FROM public.sale)))))\n  GROUP BY b.branch_id, b.branch_name, p.product_id, p.product_name, p.category\n  ORDER BY COALESCE(sum(l.quantity), (0)::bigint), COALESCE(sum(l.line_total), (0)::numeric);\n",
]

REVERSE = [
    'DROP TRIGGER IF EXISTS trg_service_detail_inventory ON public.service_detail;',
    'DROP TRIGGER IF EXISTS trg_sale_detail_inventory ON public.sale_detail;',
    'DROP VIEW IF EXISTS public.v_slow_movers;',
    'DROP VIEW IF EXISTS public.v_fast_movers;',
    'DROP VIEW IF EXISTS public.v_branch_monthly_kpi;',
    'DROP VIEW IF EXISTS public.v_service_lines;',
    'DROP VIEW IF EXISTS public.v_sale_lines;',
    'DROP FUNCTION IF EXISTS public.fn_inventory_deduct_on_service();',
    'DROP FUNCTION IF EXISTS public.fn_inventory_deduct_on_sale();',
]


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
        ("inventory", "0001_initial"),
        ("clinic", "0001_initial"),
    ]

    operations = [migrations.RunSQL(sql=FORWARD, reverse_sql=REVERSE)]
