# Generated by Django 5.2.17 on 2026-09-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_medical_record_source_txn'),
        ('sales', '0002_triggers_and_views'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='servicetransaction',
            index=models.Index(fields=['pet'], name='idx_svc_pet'),
        ),
    ]
