from django.apps import apps
from django.core.management import BaseCommand, call_command
from django.db import connection

OUR_APPS = ["clinic", "inventory", "sales", "engagement", "accounts"]


class Command(BaseCommand):
    help = (
        "Adopt a database that already holds the original vetvisiondb.sql schema and data. "
        "Adds only the columns/tables the backend needs on top, then marks the migrations as applied. "
        "Never drops or rewrites existing rows."
    )

    def handle(self, *args, **opts):
        existing = set(connection.introspection.table_names())
        models = [m for label in OUR_APPS for m in apps.get_app_config(label).get_models() if m._meta.managed]
        created, added = [], []

        with connection.schema_editor() as editor:
            for model in models:
                table = model._meta.db_table
                if table not in existing:
                    editor.create_model(model)
                    created.append(table)
                    existing.add(table)
                    continue
                with connection.cursor() as cur:
                    cols = {c.name for c in connection.introspection.get_table_description(cur, table)}
                for field in model._meta.local_fields:
                    if field.column in cols:
                        continue
                    if field.primary_key and field.get_internal_type() in ("AutoField", "BigAutoField"):
                        # Legacy link tables use a composite primary key. Keep it; add a side id column
                        # so Django can address rows.
                        editor.execute(
                            f'ALTER TABLE "{table}" ADD COLUMN "{field.column}" bigint '
                            "GENERATED BY DEFAULT AS IDENTITY UNIQUE"
                        )
                    else:
                        editor.add_field(model, field)
                        added.append(f"{table}.{field.column}")

        self.stdout.write(f"Created tables: {created or 'none'}")
        self.stdout.write(f"Added columns: {added or 'none'}")
        # Adding pet.created_at stamped every existing pet with today; use the owner's real registration date.
        if "pet.created_at" in added:
            with connection.cursor() as cur:
                cur.execute(
                    "UPDATE pet SET created_at = c.date_registered::timestamptz FROM customer c "
                    "WHERE c.customer_id = pet.customer_id AND c.date_registered IS NOT NULL"
                )
        # Free-text clinical notes outgrew the original varchar limits.
        with connection.cursor() as cur:
            cur.execute("ALTER TABLE medical_record ALTER COLUMN treatment TYPE text, ALTER COLUMN remarks TYPE text")
        for label in OUR_APPS:
            call_command("migrate", label, fake=True, verbosity=0)
        self.stdout.write(self.style.SUCCESS("Database adopted."))
