"""Forecast accuracy report for the thesis (section 3.8, "Forecasting Accuracy Testing").

Runs the same code path the Forecasting page uses, per scope (all branches, each branch), and prints the Moving Average
forecast with its back-tested MAE, MAPE and WAPE as a Markdown table.

    python manage.py forecast_report [--out docs/qa/forecast_accuracy.md]
"""
from django.core.management.base import BaseCommand
from rest_framework.test import APIClient

from accounts.models import User

SCOPES = ("All Branches", "Ibaan", "San Jose")


class Command(BaseCommand):
    help = "Print the forecast accuracy (MAE / MAPE / WAPE) for every scope as Markdown."

    def add_arguments(self, parser):
        parser.add_argument("--out", help="also write the report to this file")

    def handle(self, *args, out, **_):
        admin = User.objects.filter(role="admin", is_active=True).first()
        client = APIClient(HTTP_HOST="localhost")
        client.force_authenticate(admin)
        lines = []
        for scope in SCOPES:
            r = client.get("/api/analytics/forecast/", {"branch": scope})
            data = r.json()
            if data.get("empty"):
                continue
            m = data["method"]
            lines += [
                f"### {scope}", "",
                f"Moving Average of the previous {m['windowMonths']} complete months "
                f"({m['basedOn']['from']} to {m['basedOn']['to']}), forecasting {m['forecastMonth']}; "
                f"back-tested on the last {m['backtestMonths']} months.", "",
                "| Measure | Forecast | MAE | MAPE | WAPE |", "|---|---:|---:|---:|---:|",
            ]
            for o in data["overall"].values():
                a = o["accuracy"]
                lines.append(f"| {o['label']} | {o['forecast']:,.1f} | {a['mae']:,.1f} | {a['mape']}% | {a['wape']}% |")
            lines += ["", "| Item group | Items scored | Avg MAE (units) | Avg MAPE | Pooled WAPE |", "|---|---:|---:|---:|---:|"]
            for g, label in (("products", "Products"), ("services", "Services")):
                a = data["accuracy"][g]
                lines.append(f"| {label} | {a['count']} | {a['mae']} | {a['mape']}% | {a['wape']}% |")
            lines.append("")
        text = "\n".join(lines)
        self.stdout.write(text)
        if out:
            with open(out, "w", encoding="utf8") as f:
                f.write("# Forecast accuracy report\n\nGenerated by `python manage.py forecast_report`.\n\n" + text + "\n")
