import React from 'react'
import { useToast } from '../../components/shared/Toast'
import '../../styles/admin/reports.css'

export default function Reports() {
  const showToast = useToast()

  return (
    <main className="content">
      <div className="content-header">
        <h1>Reports</h1>
        <div className="header-filters">
          <div className="select-wrapper">
            <select defaultValue="August" onChange={() => showToast("Month filter isn't connected to any data yet.")}>
              {['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'].map(m => (
                <option key={m}>{m}</option>
              ))}
            </select>
            <svg className="select-chevron" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="6 9 12 15 18 9" /></svg>
          </div>
          <div className="select-wrapper">
            <select defaultValue="2026" onChange={() => showToast("Year filter isn't connected to any data yet.")}>
              {['2026', '2025', '2024', '2023', '2022', '2021'].map(y => (
                <option key={y}>{y}</option>
              ))}
            </select>
            <svg className="select-chevron" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="6 9 12 15 18 9" /></svg>
          </div>
          <div className="select-wrapper">
            <select defaultValue="All Branches">
              <option>All Branches</option>
              <option>Ibaan</option>
              <option>San Jose</option>
            </select>
            <svg className="select-chevron" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="6 9 12 15 18 9" /></svg>
          </div>
        </div>
      </div>

      <div className="report-cards">
        <div className="report-card">
          <div className="report-card-head">
            <div className="report-icon">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 17 9 11 13 15 21 7" /><path d="M15 7h6v6" /></svg>
            </div>
            <h3>Sales report</h3>
          </div>
          <p className="report-desc">Revenue, transactions, and branch breakdown</p>
          <button className="report-btn" onClick={() => showToast("Sales report generation isn't connected yet.")}>Generate PDF</button>
        </div>

        <div className="report-card">
          <div className="report-card-head">
            <div className="report-icon">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="7" width="18" height="13" rx="2" /><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" /><path d="M3 12h18" /></svg>
            </div>
            <h3>Inventory report</h3>
          </div>
          <p className="report-desc">Stock levels, movement, and reorder summary</p>
          <button className="report-btn" onClick={() => showToast("Inventory report generation isn't connected yet.")}>Generate PDF</button>
        </div>

        <div className="report-card">
          <div className="report-card-head">
            <div className="report-icon">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" /><circle cx="12" cy="7" r="4" /></svg>
            </div>
            <h3>Patient report</h3>
          </div>
          <p className="report-desc">Visit logs, service demand, and patient counts</p>
          <button className="report-btn" onClick={() => showToast("Patient report generation isn't connected yet.")}>Generate PDF</button>
        </div>
      </div>

      <div className="table-card">
        <div className="table-card-head">
          <h2>Recently generated reports</h2>
          <button className="export-btn" onClick={() => showToast("Export isn't connected to any data yet.")}>
            <span>Export</span>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" /><polyline points="7 10 12 15 17 10" /><line x1="12" y1="15" x2="12" y2="3" /></svg>
          </button>
        </div>
        <div className="table-scroll">
          <table>
            <thead>
              <tr>
                <th>Report name</th>
                <th>Type</th>
                <th>Branch</th>
                <th>Period</th>
                <th>Generated by</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td colSpan="5" className="empty-state">No reports generated yet.</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </main>
  )
}
