import React, { useEffect, useState } from 'react'
import { useToast } from '../../components/shared/Toast'
import { useSession } from '../../hooks/useSession'
import { fmtMoney, fmtNum, useAnalytics } from '../../hooks/useAnalytics'
import '../../styles/admin/reports.css'
import Chevron from '../../components/shared/Chevron'

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
const YEARS = ['2026', '2025', '2024', '2023', '2022', '2021']
const BRANCHES = ['Ibaan', 'San Jose']

const csvCell = (v) => {
  const s = v === null || v === undefined ? '' : String(v)
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
}
const toCsv = (rows) => rows.map((r) => r.map(csvCell).join(',')).join('\n')

// Each report is a list of sections, each with headers + rows, so the preview, print and CSV all share one shape.
function buildSections(type, d) {
  if (type === 'sales') {
    return [
      {
        title: 'Sales by branch',
        headers: ['Branch', 'Product sales', 'Service revenue', 'Total revenue', 'Profit', 'Sale transactions', 'Service transactions'],
        rows: d.sales.branches.map((b) => [b.branch, b.sales, b.services, b.total, b.profit, b.saleTxns, b.serviceTxns]),
        money: [1, 2, 3, 4]
      },
      {
        title: 'Top products by revenue',
        headers: ['Product', 'Category', 'Units sold', 'Revenue'],
        rows: d.sales.topProducts.map((p) => [p.name, p.category, p.units, p.revenue]),
        money: [3]
      },
      {
        title: 'Most availed services',
        headers: ['Service', 'Category', 'Visits', 'Revenue'],
        rows: d.services.map((s) => [s.name, s.category, s.visits, s.revenue]),
        money: [3]
      }
    ]
  }
  if (type === 'inventory') {
    return [{
      title: 'Items at or below reorder level (stock recorded in the system)',
      headers: ['Product', 'Category', 'Branch', 'Stock on hand', 'Reorder point'],
      rows: d.inventory.map((i) => [i.name, i.category, i.branch, i.stock, i.reorder_point ?? 'not set']),
      money: []
    }]
  }
  return [
    {
      title: 'Visits by species',
      headers: ['Species', 'Pets seen', 'Visits'],
      rows: d.patients.bySpecies.map((s) => [s.species, s.pets, s.visits]),
      money: []
    },
    { title: 'Registrations', headers: ['Measure', 'Value'], rows: [['New pets registered this month', d.patients.newPets]], money: [] }
  ]
}

const TITLES = { sales: 'Sales report', inventory: 'Inventory report', patients: 'Patient report' }

function ReportPreview({ report, onClose }) {
  const { type, data, branch, by, at } = report
  const sections = buildSections(type, data)

  const download = () => {
    const lines = [[TITLES[type], data.period.label, branch, `Generated by ${by}`, at]]
    sections.forEach((s) => { lines.push([], [s.title], s.headers, ...s.rows) })
    const blob = new Blob([toCsv(lines)], { type: 'text/csv;charset=utf-8' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `${type}-report-${data.period.month}.csv`
    a.click()
    URL.revokeObjectURL(a.href)
  }

  return (
    <div className="report-overlay" role="dialog" aria-modal="true" aria-label={TITLES[type]}>
      <div className="report-sheet">
        <div className="report-actions no-print">
          <button type="button" className="report-btn" onClick={() => window.print()}>Print / Save as PDF</button>
          <button type="button" className="report-btn" onClick={download}>Download CSV</button>
          <button type="button" className="report-btn secondary" onClick={onClose}>Close</button>
        </div>
        <h1>{TITLES[type]}</h1>
        <p className="report-meta">EcoVet Animal Clinic · {branch} · {data.period.label}</p>
        <p className="report-meta">Generated {at} by {by}</p>
        {sections.map((s) => (
          <section key={s.title}>
            <h2>{s.title}</h2>
            <table>
              <thead><tr>{s.headers.map((h) => <th key={h}>{h}</th>)}</tr></thead>
              <tbody>
                {s.rows.map((r, i) => (
                  <tr key={i}>{r.map((c, j) => <td key={j}>{s.money.includes(j) ? fmtMoney(c) : typeof c === 'number' ? fmtNum(c) : c}</td>)}</tr>
                ))}
                {s.rows.length === 0 && <tr><td colSpan={s.headers.length}>Nothing to report for this period.</td></tr>}
              </tbody>
            </table>
          </section>
        ))}
      </div>
    </div>
  )
}

const CARDS = [
  { type: 'sales', desc: 'Revenue, transactions, and branch breakdown', icon: <path d="M3 17 9 11 13 15 21 7M15 7h6v6" /> },
  { type: 'inventory', desc: 'Stock levels and items to reorder', icon: <><rect x="3" y="7" width="18" height="13" rx="2" /><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M3 12h18" /></> },
  { type: 'patients', desc: 'Visit logs, service demand, and patient counts', icon: <><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" /><circle cx="12" cy="7" r="4" /></> }
]

export default function Reports() {
  const showToast = useToast()
  const { session } = useSession()
  const [month, setMonth] = useState('')
  const [year, setYear] = useState('')
  const [branch, setBranch] = useState('All Branches')
  const [preview, setPreview] = useState(null)
  const [generated, setGenerated] = useState([])
  const { data, loading, error } = useAnalytics('report', { month, year, branch })

  // Default the pickers to the latest complete month of data.
  useEffect(() => {
    if (data?.period && !month) {
      const [y, m] = data.period.month.split('-')
      setYear(y)
      setMonth(String(Number(m)))
    }
  }, [data, month])

  const generate = (type) => {
    if (!data || data.empty) { showToast('There is no data to report on yet.'); return }
    const at = new Date().toLocaleString()
    const report = { type, data, branch, by: session?.name || 'Admin', at }
    setPreview(report)
    setGenerated((g) => [{ name: `${TITLES[type]} — ${data.period.label}`, type: TITLES[type], branch, period: data.period.label, by: report.by, at, report }, ...g].slice(0, 20))
  }

  return (
    <main id="main-content" tabIndex={-1} className="content">
      <div className="content-header">
        <h1>Reports</h1>
        <div className="header-filters">
          <div className="select-wrapper">
            <select value={month} onChange={(e) => setMonth(e.target.value)} aria-label="Month">
              {MONTHS.map((m, i) => <option key={m} value={i + 1}>{m}</option>)}
            </select>
            <Chevron />
          </div>
          <div className="select-wrapper">
            <select value={year} onChange={(e) => setYear(e.target.value)} aria-label="Year">
              {YEARS.map((y) => <option key={y}>{y}</option>)}
            </select>
            <Chevron />
          </div>
          <div className="select-wrapper">
            <select value={branch} onChange={(e) => setBranch(e.target.value)} aria-label="Branch">
              <option>All Branches</option>
              {BRANCHES.map((b) => <option key={b}>{b}</option>)}
            </select>
            <Chevron />
          </div>
        </div>
      </div>

      {error && <div className="load-error">Could not load report data.</div>}

      <div className="report-cards">
        {CARDS.map((c) => (
          <div className="report-card" key={c.type}>
            <div className="report-card-head">
              <div className="report-icon">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">{c.icon}</svg>
              </div>
              <h3>{TITLES[c.type]}</h3>
            </div>
            <p className="report-desc">{c.desc}</p>
            <button className="report-btn" disabled={loading} onClick={() => generate(c.type)}>{loading ? 'Loading…' : 'Generate report'}</button>
          </div>
        ))}
      </div>

      <div className="table-card">
        <div className="table-card-head">
          <h2>Recently generated reports</h2>
        </div>
        <div className="table-scroll">
          <table>
            <thead>
              <tr><th>Report name</th><th>Type</th><th>Branch</th><th>Period</th><th>Generated by</th><th /></tr>
            </thead>
            <tbody>
              {generated.map((g) => (
                <tr key={g.at + g.type}>
                  <td>{g.name}</td><td>{g.type}</td><td>{g.branch}</td><td>{g.period}</td><td>{g.by}</td>
                  <td><button type="button" className="link-btn" onClick={() => setPreview(g.report)}>Open</button></td>
                </tr>
              ))}
              {generated.length === 0 && <tr><td colSpan="6" className="empty-state">No reports generated in this session yet.</td></tr>}
            </tbody>
          </table>
        </div>
      </div>

      {preview && <ReportPreview report={preview} onClose={() => setPreview(null)} />}
    </main>
  )
}
